# Generated by Django 3.2.12 on 2023-12-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='quantity',
            new_name='initial_quantity',
        ),
        migrations.RemoveField(
            model_name='oilproduct',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='oilproduct',
            name='storage_area',
        ),
        migrations.RemoveField(
            model_name='oilproduct',
            name='storage_date',
        ),
        migrations.RemoveField(
            model_name='oilproduct',
            name='stored_quantity',
        ),
        migrations.AddField(
            model_name='harvest',
            name='creation_cause',
            field=models.CharField(default='Harvesting', max_length=15),
        ),
        migrations.AddField(
            model_name='harvest',
            name='remaining_quantity',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oilanalysis',
            name='analysis_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanage.analysisoffer'),
        ),
        migrations.AddField(
            model_name='oilanalysis',
            name='oil_mill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='dbmanage.oilmill'),
        ),
        migrations.AddField(
            model_name='oilanalysis',
            name='oil_quality',
            field=models.CharField(choices=[('EVOO', 'Extra Virgin olive oil'), ('VOO', 'Virgin olive oil'), ('L', 'Lampante olive oil'), ('R', 'Refined olive oil'), ('P', 'Olive pomace oil'), ('N', 'Not defined')], default='N', max_length=5),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='is_packaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='is_stored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oil_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packaging',
            name='oil_mill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='dbmanage.oilmill'),
        ),
        migrations.AddField(
            model_name='packaging',
            name='oil_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='dbmanage.oilproduct'),
        ),
        migrations.AddField(
            model_name='packaging',
            name='packaging_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanage.packagingoffer'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='service_type',
            field=models.CharField(choices=[('E', 'Extraction'), ('P', 'Packaging'), ('S', 'Storage'), ('A', 'Analysis'), ('N', 'Not defined')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='extractionoperation',
            name='used_machines',
            field=models.ManyToManyField(blank=True, to='dbmanage.Machine'),
        ),
        migrations.AlterField(
            model_name='oilanalysis',
            name='UV_absorbance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='oilanalysis',
            name='acidity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='oilanalysis',
            name='fatty_acid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='oilanalysis',
            name='peroxide_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OilStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_date', models.DateField()),
                ('stored_quantity', models.FloatField()),
                ('quantity_unit', models.CharField(choices=[('kg', 'Kilograms'), ('l', 'Liters')], max_length=3)),
                ('oil_mill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='dbmanage.oilmill')),
                ('oil_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='dbmanage.oilproduct')),
                ('storage_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stored_oils', to='dbmanage.storagearea')),
                ('storage_offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanage.storageoffer')),
            ],
        ),
    ]
